### ISSUE TITLE
Sonnar won't start.

### ISSUE THREAD

**Issue by rafieek** [WodKa78/-syno-packages#1]
I installed mediainfo and Mono and they are both running. But when I installed sonarr, I changed the mono path like you said. But when I try to start the package it doesnt start. So I decided to uninstall the package and try again. After trying to manually install the package again, it gets all the way to the last step but fails with a dialog message of "Not available". I restarted DSM and this fixed the install problem.

But now I am stuck on how to get sonarr actually running? It wont start...

Mono path is MONO_PATH="/var/packages/Mono/target/usr/local/bin/"

Any ideas?

**Comment by rafieek** [comment]
OK I googled and found a post here that fixed it for me so far:

Uninstall the radarr package through package center.
In DSM, Control Panel > Users and manually create a new user named "radarr" with read/write permissions to the download and media folders.
Control Panel > Users > Advanced, turn on Enable user home service.
Reinstall radarr from package center.

It was for radarr, but it works for sonarr too. I created a user named "nzbdrone".

**Comment by rafieek** [comment]
Just one last question, does your package have the ability to be updated automatically or do we have to wait for new builds by you being put here? Thank you for doing this!

**Comment by WodKa78** [comment]
updating should be done within Sonarr, actually that was the first thing i did succesfully after installing the package. Not sure why it failed on your side.

As for the not starting issue i didnt had this issue so cant't reproduce it, but since it worked for you other people will be able to find your solution here. Thanks for posting it.

**Comment by rafieek** [comment]
Here is the error I am getting:

Error occurred while executing task ApplicationUpdate: Encoding 437 data could not be found. Make sure you have correct international codeset assembly installed and enabled.

Exception
System.NotSupportedException: Encoding 437 data could not be found. Make sure you have correct international codeset assembly installed and enabled.
  at System.Text.Encoding.GetEncoding (System.Int32 codepage) [0x0024f] in /source/mono-3.x/mcs/class/referencesource/mscorlib/system/text/encoding.cs:554 
  at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToArray (System.String str) [0x0000f] in <f6bd57332ebc4902a021c0a663901ebe>:0 
  at ICSharpCode.SharpZipLib.Zip.ZipConstants.ConvertToArray (System.Int32 flags, System.String str) [0x0001f] in <f6bd57332ebc4902a021c0a663901ebe>:0 
  at ICSharpCode.SharpZipLib.Zip.ZipFile.WriteLocalEntryHeader (ICSharpCode.SharpZipLib.Zip.ZipFile+ZipUpdate update) [0x0019c] in <f6bd57332ebc4902a021c0a663901ebe>:0 
  at ICSharpCode.SharpZipLib.Zip.ZipFile.AddEntry (ICSharpCode.SharpZipLib.Zip.ZipFile workFile, ICSharpCode.SharpZipLib.Zip.ZipFile+ZipUpdate update) [0x00077] in <f6bd57332ebc4902a021c0a663901ebe>:0 
  at ICSharpCode.SharpZipLib.Zip.ZipFile.RunUpdates () [0x0011c] in <f6bd57332ebc4902a021c0a66390

**Comment by WodKa78** [comment]
U are usign the Mono package i compiled or the one offered by Synology? a quick google search learned me you miss mono-locale-extras.

**Comment by rafieek** [comment]
Well in my attempt to fix the original problem I posted about, I installed the mono from syno on top of the mono you provided. I uninstalled the syno mono shortly after everything started to work.

**Comment by WodKa78** [comment]
strange i suggest to post this issue on synocommunity as you can get much more support there then just from me ( Noob..) also i suggest to post your starting solution there as well in the same thread as you mentioned the issue so its easy available to hose with same issue.

One thing you can try is to install Synology Mono version start it and stop it but dont uninstall.

**Comment by rafieek** [comment]
Really weird. So I uninstalled sonarr and your version of Mono(the only one on my syno right now). 

Then I restarted. Installed Mono. Restarted. Installed Sonar. Restarted. Changed the Mono Path.

Now when I try to start Sonarr in package center it fails :\

**Comment by WodKa78** [comment]
first no need to uninstall sonarr all the time when you add/delete packages, 2th try to start hte service few times in a row. helped me when it didnt start at once.

**Comment by rafieek** [comment]
Trying to start sonarr about 10 times didnt help. 

Do you have both versions of Mono on your system? (But with the other version stopped)

**Comment by WodKa78** [comment]
yes with synology version stopped. Also make sure the Mono path is corrrect as is case sensitive

**Comment by rafieek** [comment]
Ok that fixed it! Looks like you need both Mono versions on the system but with the Syno version stopped. 

I really think it would be beneficial to compile all this into your readme. I can make it if you want.

**Comment by WodKa78** [comment]
Good to hear, i will update the readme.
