### ISSUE TITLE
Jackett Package?

### ISSUE THREAD

**Issue by rafieek** [WodKa78/-syno-packages#2]
Hey there again,

Thanks so much for the packages you've compiled so far. Running great on my DS218play.

Was wondering if you could/have tried compiling Jackett beta from the SynoCommunity packages?
https://github.com/SynoCommunity/spksrc/tree/master/spk/jackett

It would be awesome to use it alongside sonarr/radarr for custom torrent indexers since I have no private trackers to use.

Also, this is a long shot I am sure(from googling the issue myself) but is it even possible to compile a docker package for our realtek cpu Synology nas's? Have you tried yourself? Excuse me if that was a noob question and I dont understand how complicated it would be.

**Comment by WodKa78** [comment]
Your more welcome, i don't use torrents myself but i will try to compile Jackett for you this weekend. 

As for Docker it's not supported (yet) for ARM cpu by Synology, i did send a request to Synology to make it available for ARM but also that is a long shot. The more people request this the more attention it will get so it would help if you also request this at Synology. I am not able to do myself as this goes way over my little to non knowledge on this subject.

**Comment by rafieek** [comment]
Thanks, looking forward to see how it turns out.

I will go ahead and email synology about docker support as well. I wish there was more I could do.

**Comment by kianrafiee** [comment]
So I was trying to compile this myself. I am almost there but it seems its trying to grab dependencies from the wrong location/url:

```
make[3]: Entering directory '/home/kian/spksrc/cross/openssl'
===>  Downloading files for openssl
wget ftp://ftp.openssl.org/source/openssl-1.0.2l.tar.gz
No such file ‘openssl-1.0.2l.tar.gz’.

../../mk/spksrc.download.mk:56: recipe for target 'download_target' failed
make[3]: *** [download_target] Error 8
make[3]: Leaving directory '/home/kian/spksrc/cross/openssl'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[2]: *** [depend_target] Error 2
make[2]: Leaving directory '/home/kian/spksrc/cross/curl'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2

```

Is there anything I can do about this such as give a manual url location for curl and openssl?

This is my makefile:

```
SPK_NAME = jackett
SPK_VERS = 0.7.1483
SPK_REV = 4
SPK_ICON = src/jackett.png
DSM_UI_DIR = app

DEPENDS = cross/busybox cross/curl cross/$(SPK_NAME)
SPK_DEPENDS = "mono>=4.2.1.102-6"

MAINTAINER = SynoCommunity
DESCRIPTION = "Jackett works as a proxy server: it translates queries from apps into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps."
ADMIN_PORT = 9117
RELOAD_UI = yes
DISPLAY_NAME = Jackett
BETA = 1
CHANGELOG = Updated to version 0.7.1483

HOMEPAGE = https://github.com/Jackett/Jackett
LICENSE  = GPLv2

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh
FWPORTS          = src/${SPK_NAME}.sc
CONF_DIR         = src/conf/

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

POST_STRIP_TARGET = jackett_extra_install

REQUIRED_DSM = 5.0
UNSUPPORTED_ARCHS = $(PPC_ARCHES)

BUSYBOX_CONFIG = usrmng daemon
ENV += BUSYBOX_CONFIG="$(BUSYBOX_CONFIG)"

include ../../mk/spksrc.spk.mk

.PHONY: jackett_extra_install
jackett_extra_install:
	install -m 755 -d $(STAGING_DIR)/var
	install -m 755 -d $(STAGING_DIR)/var/.config
	install -m 755 -d $(STAGING_DIR)/var/.config/Jackett
	install -m 755 -d $(STAGING_DIR)/app
	install -m 644 src/app/config $(STAGING_DIR)/app/config
```

**Comment by kianrafiee** [comment]
OK I figured out I had to change the makefile for openssl to point to latest stable version.

Now I compiled jackett for rtd1296-6.1 successfully BUT upon installing in DSM it will not start :(

**Comment by kianrafiee** [comment]
I also changed the mono path for it to your mono package.

**Comment by WodKa78** [comment]
Had same issue as you when trying this weekend. Unfortunately no time to debug this now as traveling. Hope you can figure it out

**Comment by rafieek** [comment]
Any tips on how I can debug while your away?

**Comment by WodKa78** [comment]
Seems there are many user related issues, check the spksrc github as it's mentioned there as well. For the rest Google I guess ;)

**Comment by rafieek** [comment]
Thanks. One last thing, if I compile a mono 5.x version, can I run it side by side with your version of mono(and the mono of sync)?

**Comment by WodKa78** [comment]
Should be OK as long as you point to the correct mono location  per package

**Comment by kianrafiee** [comment]
I’m thinking the paths would be the same since they have the same package name so it won’t work.

Unless I can change the package name for my mono? Like mono5 ?

**Comment by WodKa78** [comment]
Not sure but only new version 5 should be enough for all packages to run. So are has issues with 5.x before but seems solved.

**Comment by rafieek** [comment]
Ok cool thanks.

**Comment by kianrafiee** [comment]
Welp, tried it. Got Mono 5.x to run. But Jackett still wouldn’t start. Hurmph.

Maybe you’ll have better luck once you have the time.

**Comment by WodKa78** [comment]
i close this, lets continue [here](https://github.com/SynoCommunity/spksrc/issues/3015)
