### ISSUE TITLE
Radarr package stops every once in a while

### ISSUE THREAD

**Issue by rafieek** [WodKa78/-syno-packages#3]
It seems to stop randomly through the day. I have to keep starting it again from package center. So far today it stopped three times.

Anything I can do like debugging wise to fix this? 

The radar.txt log shows nothing, just that it keeps having to start up again(when I start it from package center):

```
17-11-24 19:12:22.2|Info|Bootstrap|Starting Radarr - /volume1/@appstore/radarr/share/Radarr/Radarr.exe - Version 0.2.0.870
17-11-24 19:12:26.9|Info|MigrationLogger|*** Migrating data source=/var/packages/radarr/target/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-11-24 19:12:27.7|Info|MigrationLogger|*** Migrating data source=/var/packages/radarr/target/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-11-24 19:12:28.0|Info|Router|Application mode: Interactive
17-11-24 19:12:28.0|Info|OwinHostController|Listening on the following URLs:
17-11-24 19:12:28.0|Info|OwinHostController|  http://*:8310/
17-11-24 19:12:28.6|Info|NancyBootstrapper|Starting NzbDrone API
17-11-24 19:13:33.0|Info|Bootstrap|Starting Radarr - /volume1/@appstore/radarr/share/Radarr/Radarr.exe - Version 0.2.0.870
17-11-24 19:13:37.1|Info|MigrationLogger|*** Migrating data source=/var/packages/radarr/target/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-11-24 19:13:37.8|Info|MigrationLogger|*** Migrating data source=/var/packages/radarr/target/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-11-24 19:13:37.9|Info|Router|Application mode: Interactive
17-11-24 19:13:37.9|Info|OwinHostController|Listening on the following URLs:
17-11-24 19:13:38.0|Info|OwinHostController|  http://*:8310/
17-11-24 19:13:38.7|Info|NancyBootstrapper|Starting NzbDrone API
```

**Comment by WodKa78** [comment]
Odd, i dont have this issue, but saw elsewhere some people had same issue, they solved it by deleting and reinstalling. maybe you can try that first?

**Comment by rafieek** [comment]
Hmm yeah I'll try that. Will I have to import all my movies again? I'm guessing using a backup would just present the problem again after reinstall.

**Comment by WodKa78** [comment]
i know from the last issue you opened you created a user " nzbdrone" might be the issue here as radarr creates user sc-radarr on its own and that user needs the correct permissions. 

can't find the link anymore but since radarr is a sonarr fork searching online for solutions use sonarr instead of radarr to find more possible solutions

**Comment by rafieek** [comment]
Weird, when I try to add those users it says "The username already exists or is in use by the system"

**Comment by WodKa78** [comment]
Don't add them just give the right permissions in filestation. Radarr already made the user profile during install

**Comment by rafieek** [comment]
Hmm, sc-radarr and sc-sonarr are not in Users or Groups in my DSM

**Comment by WodKa78** [comment]
permissions--create--select from the list sc-radarr and give permissions. 
if not clear please use google as there are many tutorials to find how to set up radarr/sonarr properly.

**Comment by rafieek** [comment]
After digging I see under Shared Folders > Permissions (for a folder) > Change from Local User to System Internal Users > sc-sonarr and sc-radarr are there.

I guess thats it heh
