### ISSUE TITLE
Sonarr is not restarting

### ISSUE THREAD

**Issue by Francis2b** [WodKa78/-syno-packages#5]
Hi,

I'm running into a small problem. When I reboot my DS418 Sonarr is starting but when I ask Sonarr to restart it doesn't want to. Even if I start in the Paquet Center. If I want Sonarr to start I have to reboot my DS418.

Any idea? My a noob I know

**Comment by WodKa78** [comment]
i sometimes need to click restart twice for it to start. No idea aout a solution for now, did you already updated to the latest mono build?

**Comment by Francis2b** [comment]
When I click restart Sonarr shutdown but does not start again. I changed the Mono path and I tried with and without a / at the end it doesn't matter. The only way to restart Sonarr is to reboot my DS418

**Comment by WodKa78** [comment]
Missed the part about inapp restarting but I suggest to try to get help on the SynoCommunity github as I just build these to help myself and publish here to help others but I am not a programmer of any kind so can't help here.

**Comment by Francis2b** [comment]
Ok thanks for the advice I will ask them ;) and thanks again for your work

**Comment by WodKa78** [comment]
Welcome and hope it's get solved
